
package sisban.Clientes;

import cl.model.dao.CuentaDao;
import cl.model.dao.PreguntasDao;
import cl.model.dao.RespuestasDao;
import cl.model.dao.TransaccionesDao;
import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import javax.persistence.NoResultException;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import jpa.TblCuentas;
import jpa.TblEmpleado;
import jpa.TblTarjetas;
import jpa.TblTransacciones;
import misExcepciones.MisExcepciones;


public class TranferenciasAOtrasCuentasOBanco extends javax.swing.JFrame {
    TblCuentas tblcuenta;
    TblCuentas tblcuenta2;
    TblTarjetas tbltarjeta;
    TblEmpleado tblEmpleado;
    
    TransaccionesDao transaccionesDao;  
    
    int idCliente;
    String numCuenta;

    
    public TranferenciasAOtrasCuentasOBanco() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public TranferenciasAOtrasCuentasOBanco(int idCliente, String numCuenta) {
        initComponents();
        setLocationRelativeTo(null);
        this.idCliente = idCliente;
        this.numCuenta = numCuenta;
        Query qf = entma.createNamedQuery("TblCuentas.findByNumeroCuenta");
        qf.setParameter("numeroCuenta",numCuenta);
        tblcuenta = (TblCuentas)qf.getSingleResult();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entma = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SISBANPU").createEntityManager();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnOperacion = new javax.swing.JButton();
        txtCuenta = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("SISBAN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 16, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banco (1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 6, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setText("Numero de cuenta ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 95, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("Cliente");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 156, -1, -1));

        txtCliente.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        jPanel2.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 175, 274, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 211, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 233, 272, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        btnOperacion.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnOperacion.setText("REALIZAR OPERACION");
        btnOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOperacion)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOperacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 402, -1));

        try {
            txtCuenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCuentaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCuentaFocusLost(evt);
            }
        });
        jPanel2.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 123, 274, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        txtCuenta.setText("");
        txtCliente.setText("");
        txtCantidad.setText("");
    }
    
    private boolean camposVacios() throws MisExcepciones{
        boolean flag = false;
        if( txtCuenta.getText().trim().isEmpty()){
            flag = true;
            throw new MisExcepciones(36);
        }else if (txtCliente.getText().trim().isEmpty()){
            flag = true;
            throw new MisExcepciones(38);
        }else if(txtCantidad.getText().trim().isEmpty()){
            flag = true;
            throw new MisExcepciones(39);
        }
        return flag;
    }
    
    private String generarClaveRastreo(){
        String clave = "";
        try {
            transaccionesDao = new TransaccionesDao();
            
            do{
                clave = "";
                
                for(int i = 0; i < 30; i++){
                    clave += String.valueOf(Math.floor(Math.random() * 8 + 1)).charAt(0);
                }
            }while(transaccionesDao.existeClave(clave));            
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(this, ne.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        return clave;
    }
    
    private String generarReferencia(){
        String referencia = "";
        try {
            transaccionesDao = new TransaccionesDao();
            
            do{
                referencia = "";
                
                for(int i = 0; i < 7; i++){
                    referencia += String.valueOf(Math.floor(Math.random() * 8 + 1)).charAt(0);
                }
            }while(transaccionesDao.existeReferencia(referencia));            
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(this, ne.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        return referencia;
    }
    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if((!Character.isDigit(c) && c != '.') || txtCantidad.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void btnOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacionActionPerformed
        try {
            if(!camposVacios()){
                if(new CuentaDao().saldo(numCuenta) >= Float.valueOf(txtCantidad.getText())){
                    PreguntasDao preguntasDao = new PreguntasDao();
                    RespuestasDao respuestaDao = new RespuestasDao();
                    int strikes = 0;
                    boolean flag = false;
                    String respuestaIngresada;

                    while(strikes < 3 && !flag){
                        ArrayList pregunta = preguntasDao.pregunta();
                        respuestaIngresada = JOptionPane.showInputDialog(this, pregunta.get(1));
                        if(respuestaIngresada.equals(respuestaDao.buscarRespuesta(idCliente, Integer.valueOf(pregunta.get(0).toString())))){
                            flag = true;
                        }else{
                            strikes++;
                        }
                    }

                    if(flag){
                        entma.getTransaction().begin();
                        TblTransacciones tblTransacciones = new TblTransacciones();
                        tblTransacciones.setClaveRastreo(generarClaveRastreo());
                        tblTransacciones.setDescripción("TRASFERENCIA A NOMBRE DE: " + txtCliente.getText());
                        tblTransacciones.setMonto(Float.valueOf(txtCantidad.getText()));
                        tblTransacciones.setNumReferencia(generarReferencia());
                        tblTransacciones.setCuentaDestino(txtCuenta.getText());
                        tblTransacciones.setDestinatario(txtCliente.getText());
                        tblTransacciones.setTipoMovimiento("Cargo");
                        tblTransacciones.setBancosSucursal(tblcuenta2.getBancoSucursal().getSucursal());
                        tblTransacciones.setFecha(new Date(Calendar.getInstance().getTimeInMillis()));
                        tblTransacciones.setHora(new Time(Calendar.getInstance().getTimeInMillis()));
                        tblTransacciones.setCuentasnumeroCuenta(tblcuenta);
                        entma.persist(tblTransacciones);
                        entma.getTransaction().commit();
                        JOptionPane.showMessageDialog(this, "Operacion realizada");
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(this, "Se han hecho 3 intentos vuelva despues");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "No hay fondos suficientes");
                }
                
            }
        } catch (NumberFormatException | MisExcepciones e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnOperacionActionPerformed

    private void txtCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuentaFocusLost
        try {
            Query qf = entma.createNamedQuery("TblCuentas.findByNumeroCuenta");
            qf.setParameter("numeroCuenta", txtCuenta.getText());
            tblcuenta2 = (TblCuentas)qf.getSingleResult();
            txtCliente.setText(tblcuenta2.getClienteidCliente().getNombre());
        } catch (NoResultException e) {
            txtCuenta.setText("");
        }
    }//GEN-LAST:event_txtCuentaFocusLost

    private void txtCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuentaFocusGained
        if(txtCuenta.getText().trim().isEmpty()){
            txtCuenta.setText("");
        }
    }//GEN-LAST:event_txtCuentaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TranferenciasAOtrasCuentasOBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TranferenciasAOtrasCuentasOBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TranferenciasAOtrasCuentasOBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TranferenciasAOtrasCuentasOBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TranferenciasAOtrasCuentasOBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOperacion;
    private javax.persistence.EntityManager entma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtCuenta;
    // End of variables declaration//GEN-END:variables
}
